name: Upptime
on:
  push:
    branches: [master]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  summary:
    name: Check uptime
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@master
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
